//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.0
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiretoko.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shiretoko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;GameData&gt;
        ///  &lt;Collection Name=&quot;Masume&quot;&gt;
        ///    &lt;Masume&gt;
        ///      &lt;Name&gt;Start&lt;/Name&gt;
        ///      &lt;Index&gt;0&lt;/Index&gt;
        ///      &lt;Function&gt;StartFunction&lt;/Function&gt;
        ///      &lt;Coordinate&gt;76,506&lt;/Coordinate&gt;
        ///    &lt;/Masume&gt;
        ///    &lt;Masume&gt;
        ///      &lt;Index&gt;1&lt;/Index&gt;
        ///      &lt;Name&gt;One&lt;/Name&gt;
        ///      &lt;Function&gt;None&lt;/Function&gt;
        ///      &lt;Coordinate&gt;6,405&lt;/Coordinate&gt;
        ///    &lt;/Masume&gt;
        ///    &lt;Masume&gt;
        ///      &lt;Index&gt;2&lt;/Index&gt;
        ///      &lt;Name&gt;Two&lt;/Name&gt;
        ///      &lt;Function&gt;None&lt;/Function&gt;
        ///      &lt;Coordinate&gt;6,308&lt;/C [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefineMasume {
            get {
                return ResourceManager.GetString("DefineMasume", resourceCulture);
            }
        }
    }
}
